name: Main

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend
    uses: .github/workflows/backend.yml
  frontend:
    name: Backend
    uses: .github/workflows/frontend.yml